name: Lint code

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  test-code:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setting Up Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setting Up Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: ./frontend/pnpm.lock
          

      - name: Installing Project Dependencies
        run: pnpm install

      - name: Building Project
        run: pnpm build

      - name: Running Lint, Formater
        run: pnpm lint
